In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model

#configuro notebook para mostrar varios salidas en la misma celda
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
#amplio el output de columnas a 500
pd.set_option('display.max_columns', 500)

In [8]:
dic_all_files={'Accvict':'./cleaned/view_accvict_08_15.csv','Pers':'./cleaned/view_pers_08_15.csv','Vehic':'./cleaned/view_vehic_08_15.csv'}

dic_all_files["Accvict"]

'./cleaned/view_accvict_08_15.csv'

In [37]:
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 5.4,  3.4,  1.5,  0.4],
       [ 5.2,  4.1,  1.5,  0.1],
       [ 5.5,  4.2,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5. ,  3.2,  1.2,  0.2],
       [ 5.5,  3.5,  1.3,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 4.4,  3. ,  1.3,  0.2],
       [ 5.1,  3.4,  1.5,  0.2],
       [ 5. ,  3.5,  1.3,  0.3],
       [ 4.5,  2.3,  1.3,  0.3],
       [ 4.4,  3.2,  1.3,  0.2],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 5.1,  3.8,  1.9,  0.4],
       [ 4.8,  3. ,  1.4,  0.3],
       [ 5.1,  3.8,  1.6,  0.2],
       [ 4.6,  3.2,  1.4,  0.2],
       [ 5.3,  3.7,  1.5,  0.2],
       [ 5. ,  3.3,  1.4,  0.2],
       [ 7. ,  3.2,  4.7,  1.4],
       [ 6.4,  3.2,  4.5,  1.5],
       [ 6.9,  3.1,  4.9,  1.5],
       [ 5.5,  2.3,  4. ,  1.3],
       [ 6.5,  2.8,  4.6,  1.5],
       [ 5.7,  2.8,  4.5,  1.3],
       [ 6.3,  3.3,  4.7,  1.6],
       [ 4.9,  2.4,  3.3,  1. ],
       [ 6.6,  2.9,  4.6,  1.3],
       [ 5.2,  2.7,  3.9,  1.4],
       [ 5. ,  2. ,  3.5,  1. ],
       [ 5.9,  3. ,  4.2,  1.5],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 6.1,  2.9,  4.7,  1.4],
       [ 5.6,  2.9,  3.6,  1.3],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 5.6,  3. ,  4.5,  1.5],
       [ 5.8,  2.7,  4.1,  1. ],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 5.6,  2.5,  3.9,  1.1],
       [ 5.9,  3.2,  4.8,  1.8],
       [ 6.1,  2.8,  4. ,  1.3],
       [ 6.3,  2.5,  4.9,  1.5],
       [ 6.1,  2.8,  4.7,  1.2],
       [ 6.4,  2.9,  4.3,  1.3],
       [ 6.6,  3. ,  4.4,  1.4],
       [ 6.8,  2.8,  4.8,  1.4],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 6. ,  2.9,  4.5,  1.5],
       [ 5.7,  2.6,  3.5,  1. ],
       [ 5.5,  2.4,  3.8,  1.1],
       [ 5.5,  2.4,  3.7,  1. ],
       [ 5.8,  2.7,  3.9,  1.2],
       [ 6. ,  2.7,  5.1,  1.6],
       [ 5.4,  3. ,  4.5,  1.5],
       [ 6. ,  3.4,  4.5,  1.6],
       [ 6.7,  3.1,  4.7,  1.5],
       [ 6.3,  2.3,  4.4,  1.3],
       [ 5.6,  3. ,  4.1,  1.3],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 5.5,  2.6,  4.4,  1.2],
       [ 6.1,  3. ,  4.6,  1.4],
       [ 5.8,  2.6,  4. ,  1.2],
       [ 5. ,  2.3,  3.3,  1. ],
       [ 5.6,  2.7,  4.2,  1.3],
       [ 5.7,  3. ,  4.2,  1.2],
       [ 5.7,  2.9,  4.2,  1.3],
       [ 6.2,  2.9,  4.3,  1.3],
       [ 5.1,  2.5,  3. ,  1.1],
       [ 5.7,  2.8,  4.1,  1.3],
       [ 6.3,  3.3,  6. ,  2.5],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 7.1,  3. ,  5.9,  2.1],
       [ 6.3,  2.9,  5.6,  1.8],
       [ 6.5,  3. ,  5.8,  2.2],
       [ 7.6,  3. ,  6.6,  2.1],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 6.7,  2.5,  5.8,  1.8],
       [ 7.2,  3.6,  6.1,  2.5],
       [ 6.5,  3.2,  5.1,  2. ],
       [ 6.4,  2.7,  5.3,  1.9],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 5.7,  2.5,  5. ,  2. ],
       [ 5.8,  2.8,  5.1,  2.4],
       [ 6.4,  3.2,  5.3,  2.3],
       [ 6.5,  3. ,  5.5,  1.8],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 7.7,  2.6,  6.9,  2.3],
       [ 6. ,  2.2,  5. ,  1.5],
       [ 6.9,  3.2,  5.7,  2.3],
       [ 5.6,  2.8,  4.9,  2. ],
       [ 7.7,  2.8,  6.7,  2. ],
       [ 6.3,  2.7,  4.9,  1.8],
       [ 6.7,  3.3,  5.7,  2.1],
       [ 7.2,  3.2,  6. ,  1.8],
       [ 6.2,  2.8,  4.8,  1.8],
       [ 6.1,  3. ,  4.9,  1.8],
       [ 6.4,  2.8,  5.6,  2.1],
       [ 7.2,  3. ,  5.8,  1.6],
       [ 7.4,  2.8,  6.1,  1.9],
       [ 7.9,  3.8,  6.4,  2. ],
       [ 6.4,  2.8,  5.6,  2.2],
       [ 6.3,  2.8,  5.1,  1.5],
       [ 6.1,  2.6,  5.6,  1.4],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 6.3,  3.4,  5.6,  2.4],
       [ 6.4,  3.1,  5.5,  1.8],
       [ 6. ,  3. ,  4.8,  1.8],
       [ 6.9,  3.1,  5.4,  2.1],
       [ 6.7,  3.1,  5.6,  2.4],
       [ 6.9,  3.1,  5.1,  2.3],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6.8,  3.2,  5.9,  2.3],
       [ 6.7,  3.3,  5.7,  2.5],
       [ 6.7,  3. ,  5.2,  2.3],
       [ 6.3,  2.5,  5. ,  1.9],
       [ 6.5,  3. ,  5.2,  2. ],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 5.9,  3. ,  5.1,  1.8]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
print ("-----------------------------------------------------\n")
print ("VISTA CON LOS DATOS DE ACCIDENTES DESDE 2008 A 2015\n")
print ("-----------------------------------------------------\n")

df_acc=pd.read_csv(dic_all_files["Accvict"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

print ("-----------------------------------------------------\n")
print ("VISTA CON LOS DATOS DE PERSONAS DESDE 2008 A 2015\n")
print ("-----------------------------------------------------\n")

df_acc=pd.read_csv(dic_all_files["Pers"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

print ("-----------------------------------------------------\n")
print ("VISTA CON LOS DATOS DE VEHICULOS DESDE 2008 A 2015\n")
print ("-----------------------------------------------------\n")

df_acc=pd.read_csv(dic_all_files["Vehic"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

-----------------------------------------------------

VISTA CON LOS DATOS DE ACCIDENTES DESDE 2008 A 2015

-----------------------------------------------------

,ID_ACCIDENTE,ANIO,MES,HORA,DIASEMANA,PROVINCIA,COMUNIDAD_AUTONOMA,TOT_VICTIMAS,TOT_MUERTOS,TOT_HERIDOS_GRAVES,TOT_HERIDOS_LEVES,TOT_VEHICULOS_IMPLICADOS,ZONA,ZONA_AGRUPADA,RED_CARRETERA,TIPO_VIA,SUPERFICIE_CALZADA,LUMINOSIDAD,FACTORES_ATMOSFERICOS,VISIBILIDAD_RESTRINGIDA,TIPO_ACCIDENTE
0,2008480000372,2008,4,7,5,48,17,4,0,0,4,1,1,1,3,2,2,3,1,8,71
1,2008250021218,2008,3,14,7,25,9,1,0,1,0,1,1,1,2,5,1,1,9,8,22
2,2008430024095,2008,10,12,7,43,9,1,0,0,1,1,1,1,4,5,1,1,1,0,68
3,2008430022973,2008,4,18,2,43,9,1,0,0,1,2,1,1,4,5,1,1,1,0,14
4,2008250021457,2008,5,19,5,25,9,1,0,1,0,1,1,1,4,9,9,1,9,8,66

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 711902 entries, 0 to 711901
Data columns (total 21 columns):
ID_ACCIDENTE                711902 non-null object
ANIO                        711902 non-null int64
MES                         711902 non-null int64
HORA                        711902 non-null int64
DIASEMANA                   711902 non-null int64
PROVINCIA                   711902 non-null int64
COMUNIDAD_AUTONOMA          711902 non-null int64
TOT_VICTIMAS                711902 non-null int64
TOT_MUERTOS                 711902 non-null int64
TOT_HERIDOS_GRAVES          711902 non-null int64
TOT_HERIDOS_LEVES           711902 non-null int64
TOT_VEHICULOS_IMPLICADOS    711902 non-null int64
ZONA                        711902 non-null int64
ZONA_AGRUPADA               711902 non-null int64
RED_CARRETERA               711902 non-null int64
TIPO_VIA                    711902 non-null int64
SUPERFICIE_CALZADA          711902 non-null int64
LUMINOSIDAD                 711902 non-null int64
FACTORES_ATMOSFERICOS       711902 non-null int64
VISIBILIDAD_RESTRINGIDA     711902 non-null int64
TIPO_ACCIDENTE              711902 non-null int64
dtypes: int64(20), object(1)
memory usage: 114.1+ MB
-----------------------------------------------------

VISTA CON LOS DATOS DE PERSONAS DESDE 2008 A 2015

-----------------------------------------------------

,ID_ACCIDENTE,ID_VEHICULO,ID_PERSONA,ID_CONDUCTOR,ID_PASAJERO,ID_PEATON,EDAD,ANIO_PERMISO,MANIOBRAS,INFRACC_VELOCIDAD,INFRACC_PEATON,ANIO
0,2008010000001,1,2,1,1,1,32,9999,21,4,9,2008
1,2008010000001,2,2,1,1,1,60,9999,21,4,9,2008
2,2008010000001,2,2,1,2,1,23,9999,21,4,9,2008
3,2008010000001,1,2,1,2,1,28,9999,21,4,9,2008
4,2008010000001,2,1,2,1,1,61,1999,1,5,9,2008

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1724736 entries, 0 to 1724735
Data columns (total 12 columns):
ID_ACCIDENTE         object
ID_VEHICULO          int64
ID_PERSONA           int64
ID_CONDUCTOR         int64
ID_PASAJERO          int64
ID_PEATON            int64
EDAD                 int64
ANIO_PERMISO         int64
MANIOBRAS            int64
INFRACC_VELOCIDAD    int64
INFRACC_PEATON       int64
ANIO                 int64
dtypes: int64(11), object(1)
memory usage: 157.9+ MB
-----------------------------------------------------

VISTA CON LOS DATOS DE VEHICULOS DESDE 2008 A 2015

-----------------------------------------------------

,ID_ACCIDENTE,ID_VEHICULO,ANIO_MATRICULA_VEHICULO,MES_MATRICULA_VEHICULO,TIPO_VEHICULO,NUMERO_OCUPANTES_VEH,ANIO
0,2008410002330,2,9999,99,22,1,2008
1,2008520000162,2,1991,99,22,1,2008
2,2009460000665,3,2004,1,22,1,2008
3,2008460007725,1,2003,1,22,5,2008
4,2008410000371,1,2006,7,22,1,2008

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1239593 entries, 0 to 1239592
Data columns (total 7 columns):
ID_ACCIDENTE               1239593 non-null object
ID_VEHICULO                1239593 non-null int64
ANIO_MATRICULA_VEHICULO    1239593 non-null int64
MES_MATRICULA_VEHICULO     1239593 non-null int64
TIPO_VEHICULO              1239593 non-null int64
NUMERO_OCUPANTES_VEH       1239593 non-null int64
ANIO                       1239593 non-null int64
dtypes: int64(6), object(1)
memory usage: 66.2+ MB

In [91]:
dic_all_files={'Accvict':"./cleaned/view_accvict_08_15.csv",'Pers':"./cleaned/view_pers_08_15.csv",'Vehic':"./cleaned/view_pers_08_15.csv"}

df_acc=pd.read_csv(dic_all_files["Pers"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

df_acc_2015=df_acc[df_acc['ANIO']==2015]
df_acc_2015=df_acc_2015[['TOT_VICTIMAS','TOT_MUERTOS']]
df_acc_2015.head(5)

df_acc_2015.as_matrix()
KM=KMeans(init='random',n_clusters=3).fit(df_acc_2015)
#Extraemos las medias

L=KM.cluster_centers_

#Extraemos los valores usados para los calculos

Lab=KM.labels_

print(Lab)


fig1= plt.figure(1)
fig.suptitle("Ejemplo de k-medias",fontsize=15)
plot3= plt.scatter(df_acc_2015.values[:,0], df_acc_2015.values[:,1], c=Lab, alpha=0.75)

plt.show()

,ID_ACCIDENTE,ID_VEHICULO,ID_PERSONA,ID_CONDUCTOR,ID_PASAJERO,ID_PEATON,EDAD,SEXO,ANIO_PERMISO,MANIOBRAS,INFRACC_VELOCIDAD,INFRACC_PEATON,ANIO
0,"2,00801E+12",1,2,1,1,1,32,M,9999,18,3,9,2008
1,"2,00801E+12",2,2,1,1,1,60,M,9999,18,3,9,2008
2,"2,00801E+12",2,2,1,2,1,23,V,9999,18,3,9,2008
3,"2,00801E+12",1,2,1,2,1,28,M,9999,18,3,9,2008
4,"2,00801E+12",2,1,2,1,1,61,V,9999,1,5,9,2008

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1633782 entries, 0 to 1633781
Data columns (total 13 columns):
ID_ACCIDENTE         1633782 non-null object
ID_VEHICULO          1633782 non-null int64
ID_PERSONA           1633782 non-null int64
ID_CONDUCTOR         1633782 non-null int64
ID_PASAJERO          1633782 non-null int64
ID_PEATON            1633782 non-null int64
EDAD                 1633782 non-null int64
SEXO                 1633782 non-null object
ANIO_PERMISO         1633782 non-null int64
MANIOBRAS            1633782 non-null int64
INFRACC_VELOCIDAD    1633782 non-null int64
INFRACC_PEATON       1633782 non-null int64
ANIO                 1633782 non-null int64
dtypes: int64(11), object(2)
memory usage: 162.0+ MB

KeyError: "['TOT_VICTIMAS' 'TOT_MUERTOS'] not in index"

In [87]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
iris = load_iris()
pca = PCA(n_components=2).fit(iris.data)
pca_2d = pca.transform(iris.data)
pca_2d

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 5.4,  3.4,  1.5,  0.4],
       [ 5.2,  4.1,  1.5,  0.1],
       [ 5.5,  4.2,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5. ,  3.2,  1.2,  0.2],
       [ 5.5,  3.5,  1.3,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 4.4,  3. ,  1.3,  0.2],
       [ 5.1,  3.4,  1.5,  0.2],
       [ 5. ,  3.5,  1.3,  0.3],
       [ 4.5,  2.3,  1.3,  0.3],
       [ 4.4,  3.2,  1.3,  0.2],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 5.1,  3.8,  1.9,  0.4],
       [ 4.8,  3. ,  1.4,  0.3],
       [ 5.1,  3.8,  1.6,  0.2],
       [ 4.6,  3.2,  1.4,  0.2],
       [ 5.3,  3.7,  1.5,  0.2],
       [ 5. ,  3.3,  1.4,  0.2],
       [ 7. ,  3.2,  4.7,  1.4],
       [ 6.4,  3.2,  4.5,  1.5],
       [ 6.9,  3.1,  4.9,  1.5],
       [ 5.5,  2.3,  4. ,  1.3],
       [ 6.5,  2.8,  4.6,  1.5],
       [ 5.7,  2.8,  4.5,  1.3],
       [ 6.3,  3.3,  4.7,  1.6],
       [ 4.9,  2.4,  3.3,  1. ],
       [ 6.6,  2.9,  4.6,  1.3],
       [ 5.2,  2.7,  3.9,  1.4],
       [ 5. ,  2. ,  3.5,  1. ],
       [ 5.9,  3. ,  4.2,  1.5],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 6.1,  2.9,  4.7,  1.4],
       [ 5.6,  2.9,  3.6,  1.3],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 5.6,  3. ,  4.5,  1.5],
       [ 5.8,  2.7,  4.1,  1. ],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 5.6,  2.5,  3.9,  1.1],
       [ 5.9,  3.2,  4.8,  1.8],
       [ 6.1,  2.8,  4. ,  1.3],
       [ 6.3,  2.5,  4.9,  1.5],
       [ 6.1,  2.8,  4.7,  1.2],
       [ 6.4,  2.9,  4.3,  1.3],
       [ 6.6,  3. ,  4.4,  1.4],
       [ 6.8,  2.8,  4.8,  1.4],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 6. ,  2.9,  4.5,  1.5],
       [ 5.7,  2.6,  3.5,  1. ],
       [ 5.5,  2.4,  3.8,  1.1],
       [ 5.5,  2.4,  3.7,  1. ],
       [ 5.8,  2.7,  3.9,  1.2],
       [ 6. ,  2.7,  5.1,  1.6],
       [ 5.4,  3. ,  4.5,  1.5],
       [ 6. ,  3.4,  4.5,  1.6],
       [ 6.7,  3.1,  4.7,  1.5],
       [ 6.3,  2.3,  4.4,  1.3],
       [ 5.6,  3. ,  4.1,  1.3],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 5.5,  2.6,  4.4,  1.2],
       [ 6.1,  3. ,  4.6,  1.4],
       [ 5.8,  2.6,  4. ,  1.2],
       [ 5. ,  2.3,  3.3,  1. ],
       [ 5.6,  2.7,  4.2,  1.3],
       [ 5.7,  3. ,  4.2,  1.2],
       [ 5.7,  2.9,  4.2,  1.3],
       [ 6.2,  2.9,  4.3,  1.3],
       [ 5.1,  2.5,  3. ,  1.1],
       [ 5.7,  2.8,  4.1,  1.3],
       [ 6.3,  3.3,  6. ,  2.5],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 7.1,  3. ,  5.9,  2.1],
       [ 6.3,  2.9,  5.6,  1.8],
       [ 6.5,  3. ,  5.8,  2.2],
       [ 7.6,  3. ,  6.6,  2.1],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 6.7,  2.5,  5.8,  1.8],
       [ 7.2,  3.6,  6.1,  2.5],
       [ 6.5,  3.2,  5.1,  2. ],
       [ 6.4,  2.7,  5.3,  1.9],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 5.7,  2.5,  5. ,  2. ],
       [ 5.8,  2.8,  5.1,  2.4],
       [ 6.4,  3.2,  5.3,  2.3],
       [ 6.5,  3. ,  5.5,  1.8],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 7.7,  2.6,  6.9,  2.3],
       [ 6. ,  2.2,  5. ,  1.5],
       [ 6.9,  3.2,  5.7,  2.3],
       [ 5.6,  2.8,  4.9,  2. ],
       [ 7.7,  2.8,  6.7,  2. ],
       [ 6.3,  2.7,  4.9,  1.8],
       [ 6.7,  3.3,  5.7,  2.1],
       [ 7.2,  3.2,  6. ,  1.8],
       [ 6.2,  2.8,  4.8,  1.8],
       [ 6.1,  3. ,  4.9,  1.8],
       [ 6.4,  2.8,  5.6,  2.1],
       [ 7.2,  3. ,  5.8,  1.6],
       [ 7.4,  2.8,  6.1,  1.9],
       [ 7.9,  3.8,  6.4,  2. ],
       [ 6.4,  2.8,  5.6,  2.2],
       [ 6.3,  2.8,  5.1,  1.5],
       [ 6.1,  2.6,  5.6,  1.4],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 6.3,  3.4,  5.6,  2.4],
       [ 6.4,  3.1,  5.5,  1.8],
       [ 6. ,  3. ,  4.8,  1.8],
       [ 6.9,  3.1,  5.4,  2.1],
       [ 6.7,  3.1,  5.6,  2.4],
       [ 6.9,  3.1,  5.1,  2.3],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6.8,  3.2,  5.9,  2.3],
       [ 6.7,  3.3,  5.7,  2.5],
       [ 6.7,  3. ,  5.2,  2.3],
       [ 6.3,  2.5,  5. ,  1.9],
       [ 6.5,  3. ,  5.2,  2. ],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 5.9,  3. ,  5.1,  1.8]])

array([[-2.68420713,  0.32660731],
       [-2.71539062, -0.16955685],
       [-2.88981954, -0.13734561],
       [-2.7464372 , -0.31112432],
       [-2.72859298,  0.33392456],
       [-2.27989736,  0.74778271],
       [-2.82089068, -0.08210451],
       [-2.62648199,  0.17040535],
       [-2.88795857, -0.57079803],
       [-2.67384469, -0.1066917 ],
       [-2.50652679,  0.65193501],
       [-2.61314272,  0.02152063],
       [-2.78743398, -0.22774019],
       [-3.22520045, -0.50327991],
       [-2.64354322,  1.1861949 ],
       [-2.38386932,  1.34475434],
       [-2.6225262 ,  0.81808967],
       [-2.64832273,  0.31913667],
       [-2.19907796,  0.87924409],
       [-2.58734619,  0.52047364],
       [-2.3105317 ,  0.39786782],
       [-2.54323491,  0.44003175],
       [-3.21585769,  0.14161557],
       [-2.30312854,  0.10552268],
       [-2.35617109, -0.03120959],
       [-2.50791723, -0.13905634],
       [-2.469056  ,  0.13788731],
       [-2.56239095,  0.37468456],
       [-2.63982127,  0.31929007],
       [-2.63284791, -0.19007583],
       [-2.58846205, -0.19739308],
       [-2.41007734,  0.41808001],
       [-2.64763667,  0.81998263],
       [-2.59715948,  1.10002193],
       [-2.67384469, -0.1066917 ],
       [-2.86699985,  0.0771931 ],
       [-2.62522846,  0.60680001],
       [-2.67384469, -0.1066917 ],
       [-2.98184266, -0.48025005],
       [-2.59032303,  0.23605934],
       [-2.77013891,  0.27105942],
       [-2.85221108, -0.93286537],
       [-2.99829644, -0.33430757],
       [-2.4055141 ,  0.19591726],
       [-2.20883295,  0.44269603],
       [-2.71566519, -0.24268148],
       [-2.53757337,  0.51036755],
       [-2.8403213 , -0.22057634],
       [-2.54268576,  0.58628103],
       [-2.70391231,  0.11501085],
       [ 1.28479459,  0.68543919],
       [ 0.93241075,  0.31919809],
       [ 1.46406132,  0.50418983],
       [ 0.18096721, -0.82560394],
       [ 1.08713449,  0.07539039],
       [ 0.64043675, -0.41732348],
       [ 1.09522371,  0.28389121],
       [-0.75146714, -1.00110751],
       [ 1.04329778,  0.22895691],
       [-0.01019007, -0.72057487],
       [-0.5110862 , -1.26249195],
       [ 0.51109806, -0.10228411],
       [ 0.26233576, -0.5478933 ],
       [ 0.98404455, -0.12436042],
       [-0.174864  , -0.25181557],
       [ 0.92757294,  0.46823621],
       [ 0.65959279, -0.35197629],
       [ 0.23454059, -0.33192183],
       [ 0.94236171, -0.54182226],
       [ 0.0432464 , -0.58148945],
       [ 1.11624072, -0.08421401],
       [ 0.35678657, -0.06682383],
       [ 1.29646885, -0.32756152],
       [ 0.92050265, -0.18239036],
       [ 0.71400821,  0.15037915],
       [ 0.89964086,  0.32961098],
       [ 1.33104142,  0.24466952],
       [ 1.55739627,  0.26739258],
       [ 0.81245555, -0.16233157],
       [-0.30733476, -0.36508661],
       [-0.07034289, -0.70253793],
       [-0.19188449, -0.67749054],
       [ 0.13499495, -0.31170964],
       [ 1.37873698, -0.42120514],
       [ 0.58727485, -0.48328427],
       [ 0.8072055 ,  0.19505396],
       [ 1.22042897,  0.40803534],
       [ 0.81286779, -0.370679  ],
       [ 0.24519516, -0.26672804],
       [ 0.16451343, -0.67966147],
       [ 0.46303099, -0.66952655],
       [ 0.89016045, -0.03381244],
       [ 0.22887905, -0.40225762],
       [-0.70708128, -1.00842476],
       [ 0.35553304, -0.50321849],
       [ 0.33112695, -0.21118014],
       [ 0.37523823, -0.29162202],
       [ 0.64169028,  0.01907118],
       [-0.90846333, -0.75156873],
       [ 0.29780791, -0.34701652],
       [ 2.53172698, -0.01184224],
       [ 1.41407223, -0.57492506],
       [ 2.61648461,  0.34193529],
       [ 1.97081495, -0.18112569],
       [ 2.34975798, -0.04188255],
       [ 3.39687992,  0.54716805],
       [ 0.51938325, -1.19135169],
       [ 2.9320051 ,  0.35237701],
       [ 2.31967279, -0.24554817],
       [ 2.91813423,  0.78038063],
       [ 1.66193495,  0.2420384 ],
       [ 1.80234045, -0.21615461],
       [ 2.16537886,  0.21528028],
       [ 1.34459422, -0.77641543],
       [ 1.5852673 , -0.53930705],
       [ 1.90474358,  0.11881899],
       [ 1.94924878,  0.04073026],
       [ 3.48876538,  1.17154454],
       [ 3.79468686,  0.25326557],
       [ 1.29832982, -0.76101394],
       [ 2.42816726,  0.37678197],
       [ 1.19809737, -0.60557896],
       [ 3.49926548,  0.45677347],
       [ 1.38766825, -0.20403099],
       [ 2.27585365,  0.33338653],
       [ 2.61419383,  0.55836695],
       [ 1.25762518, -0.179137  ],
       [ 1.29066965, -0.11642525],
       [ 2.12285398, -0.21085488],
       [ 2.3875644 ,  0.46251925],
       [ 2.84096093,  0.37274259],
       [ 3.2323429 ,  1.37052404],
       [ 2.15873837, -0.21832553],
       [ 1.4431026 , -0.14380129],
       [ 1.77964011, -0.50146479],
       [ 3.07652162,  0.68576444],
       [ 2.14498686,  0.13890661],
       [ 1.90486293,  0.04804751],
       [ 1.16885347, -0.1645025 ],
       [ 2.10765373,  0.37148225],
       [ 2.31430339,  0.18260885],
       [ 1.92245088,  0.40927118],
       [ 1.41407223, -0.57492506],
       [ 2.56332271,  0.2759745 ],
       [ 2.41939122,  0.30350394],
       [ 1.94401705,  0.18741522],
       [ 1.52566363, -0.37502085],
       [ 1.76404594,  0.07851919],
       [ 1.90162908,  0.11587675],
       [ 1.38966613, -0.28288671]])